# Couldn't find class for name Navigation
# Code Generated by ZenTest v. 4.1.4
#                 classname: asrt / meth =  ratio%
# Cinnamon::Navigation::PagesArray:    0 /   10 =   0.00%

require 'test/unit/testcase'
require 'test/unit' if $0 == __FILE__

module TestCinnamon
  module TestNavigation
    class TestPagesArray < Test::Unit::TestCase
      def test_add
        raise NotImplementedError, 'Need to write test_add'
      end

      def test_all
        raise NotImplementedError, 'Need to write test_all'
      end

      def test_any_eh
        raise NotImplementedError, 'Need to write test_any_eh'
      end

      def test_dirty_order
        raise NotImplementedError, 'Need to write test_dirty_order'
      end

      def test_dirty_order_equals
        raise NotImplementedError, 'Need to write test_dirty_order_equals'
      end

      def test_find
        raise NotImplementedError, 'Need to write test_find'
      end

      def test_first
        raise NotImplementedError, 'Need to write test_first'
      end

      def test_lt2
        raise NotImplementedError, 'Need to write test_lt2'
      end

      def test_remove
        raise NotImplementedError, 'Need to write test_remove'
      end

      def test_remove_all
        raise NotImplementedError, 'Need to write test_remove_all'
      end
    end
  end
end

# Number of errors detected: 12
